services:
  mongo-setup:
    image: mongo:latest
    container_name: mongo-setup
    depends_on:
      - configsvr
      - mongos
      # add your shard services here too, e.g.
      - shard1
      - shard2
      - shard3
    volumes:
      - ./init:/scripts:ro
    entrypoint: ["/bin/bash", "/scripts/00-setup.sh"]
    networks:
      - mongo
    restart: "no"

  configsvr:
    image: mongo:latest
    container_name: mongo-configsvr
    command:
      [
        "mongod",
        "--configsvr",
        "--replSet",
        "rs-config",
        "--port",
        "27019",
        "--bind_ip_all",
      ]
    volumes:
      - configsvr_data:/data/db
      - configsvr_config:/data/configdb
    networks:
      - mongo

  shard1:
    image: mongo:latest
    container_name: mongo-shard-1
    command:
      [
        "mongod",
        "--shardsvr",
        "--replSet",
        "rs-shard-1",
        "--port",
        "27017",
        "--bind_ip_all",
      ]
    volumes:
      - shard1_data:/data/db
    networks:
      - mongo

  shard2:
    image: mongo:latest
    container_name: mongo-shard-2
    command:
      [
        "mongod",
        "--shardsvr",
        "--replSet",
        "rs-shard-2",
        "--port",
        "27017",
        "--bind_ip_all",
      ]
    volumes:
      - shard2_data:/data/db
    networks:
      - mongo

  shard3:
    image: mongo:latest
    container_name: mongo-shard-3
    command:
      [
        "mongod",
        "--shardsvr",
        "--replSet",
        "rs-shard-3",
        "--port",
        "27017",
        "--bind_ip_all",
      ]
    volumes:
      - shard3_data:/data/db
    networks:
      - mongo

  mongos:
    image: mongo:latest
    container_name: mongo-mongos
    depends_on:
      - configsvr
    command:
      [
        "mongos",
        "--configdb",
        "rs-config/configsvr:27019",
        "--bind_ip_all",
        "--port",
        "27017",
      ]
    ports:
      - "27017:27017"
    networks:
      - mongo
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  configsvr_config:
  configsvr_data:
  shard1_data:
  shard2_data:
  shard3_data:

networks:
  mongo:
    name: mongo-network
    driver: bridge
